# =========================================================
# 08_report.R -- turn the result tables into a readable results section
#
# Writes results.md next to the CSVs for each experiment: the same structure
# used in the write-up (preprocessing, tracking correlations, LMM, exaggeration)
# with every number pulled from the tables that were just computed, so the text
# and the CSVs can never drift apart.
# =========================================================

# pull one row out of an ANOVA table by effect name (order-insensitive)
get_effect <- function(tab, ...) {
  wanted <- sort(unlist(strsplit(c(...), ":")))
  hit <- vapply(tab$effect, function(e)
    identical(sort(unlist(strsplit(gsub("`", "", e), ":"))), wanted), logical(1))
  if (!any(hit)) return(NULL)
  tab[which(hit)[1], ]
}

f_line <- function(row) {
  if (is.null(row)) return("not estimated")
  fmt_F(row$F, row$df1, row$df2, row$p)
}

# factors print as their integer codes inside cat(); always go through this.
# emmeans also decorates level names ("X10", "variance_level5"), so strip that.
chr <- function(x, noise = NULL) {
  x <- as.character(x)
  if (!is.null(noise)) x <- gsub(noise, "", x, fixed = TRUE)
  gsub("(^|[ (])X(?=[0-9])", "\\1", x, perl = TRUE)
}

epoc_report <- function(res, exp, path) {

  noise  <- exp$noise_var
  nice   <- exp$noise
  two    <- "condition" %in% names(res$lmm$slopes)
  con    <- file(path, open = "wt"); on.exit(close(con))
  w      <- function(...) log_line(con, ...)

  w("# ", exp$label)
  w("")
  w("_Generated by analysis/run_all.R on ", format(Sys.time(), "%Y-%m-%d %H:%M"), "._")
  w("")

  # ---------------- preprocessing ----------------
  w("## Data preprocessing")
  w("")
  if (RANDOM_MODE == "full")
    w("**Alternative pipeline:** mixed models start from the maximal random-effects structure and always keep ",
      "a by-participant slope on the continuous predictor (see `FULL_LADDER` in 05_lmm.R). ")
  if (TRUE_VALUE == "shown")
    w("**Alternative pipeline:** the objective value of each trial is the mean of the squares actually displayed ",
      "(from `array_values`), not the logged `meanVal`. ")
  w("Trials with a report of ", NO_RESPONSE, " (the scale's starting value, recorded when the ",
    "participant clicked without moving onto the scale) were treated as missing responses and removed. ",
    "Trials with RT < ", RT_MIN, " ms or RT > ", RT_MAX, " ms were removed, followed by ",
    "within-participant +/-", RT_SD_TRIM, " SD trimming on RT and removal of trials whose ",
    "absolute deviation from the objective mean exceeded ", MAX_ABS_ERR, " scale units. ",
    "Participants retaining fewer than ", round(MIN_RETENTION * 100), "% of their trials, or whose ",
    "Spearman correlation between objective mean and report was <= ", MIN_SPEARMAN, ", were excluded.")
  w("")
  if (!is.null(res$exclusions) && nrow(res$exclusions)) {
    ex <- res$exclusions %>% tidyr::pivot_wider(names_from = stage, values_from = n_participants)
    for (i in seq_len(nrow(ex))) {
      r <- ex[i, ]
      w("- ", r$condition, " condition: ", r$started, " started, ",
        if (isTRUE(r$later_session > 0))
          paste0(r$later_session, " excluded as a second session (already took part in the other condition), "),
        r$incomplete_session, " excluded for an incomplete session, ",
        r$low_retention, " for low trial retention, ",
        r$low_tracking, " for not tracking the stimulus, leaving **", r$analysed, "**.")
    }
    w("")
  }
  d <- res$descriptives
  for (i in seq_len(nrow(d))) {
    w("- ", chr(d$condition[i]), ": N = ", d$n_participants[i], ", ", d$n_trials[i],
      " trials (M = ", d$trials_per_part[i], " per participant), mean absolute error = ",
      d$mean_abs_error[i], " scale units.")
  }
  w("")

  # ---------------- correlations ----------------
  w("## Single-subject correlation analysis")
  w("")
  w("Within-participant correlations between the objective mean and the reported value were ",
    "computed for each level of ", nice, ", Fisher-z transformed, and entered into ",
    if (two) paste0("a mixed ANOVA (", nice, " within, condition between).")
    else paste0("a repeated-measures ANOVA over ", nice, "."))
  w("")
  cs <- res$corr$summary
  for (cond in levels(droplevels(cs$condition))) {
    part <- cs %>% filter(condition == cond)
    w("- ", cond, ": mean r = ",
      paste(sprintf("%s (%s)", fmt_num(part$mean_r, 2), chr(part[[noise]])), collapse = ", "), ".")
  }
  w("")
  ca <- res$corr$anova
  w("- Main effect of ", nice, ": ", f_line(get_effect(ca, noise)), ".")
  if (two) {
    w("- Main effect of condition: ", f_line(get_effect(ca, "condition")), ".")
    w("- ", nice, " x condition: ", f_line(get_effect(ca, paste0("condition:", noise))), ".")
  }
  w("")
  ph <- res$corr$posthoc %>% filter(comparison_set == "noise_within_condition")
  if (!nrow(ph)) ph <- res$corr$posthoc %>% filter(comparison_set == "noise_overall")
  if (nrow(ph)) {
    w("Pairwise comparisons (Tukey-adjusted):")
    w("")
    for (i in seq_len(nrow(ph))) {
      lab <- if ("condition" %in% names(ph)) paste0(chr(ph$condition[i]), ", ") else ""
      w("- ", lab, chr(ph$contrast[i], noise), ": difference in z = ", fmt_num(ph$estimate[i], 3),
        ", ", fmt_p(ph$p.value[i]), ".")
    }
    w("")
  }

  # ---------------- within-condition models ----------------
  if (!is.null(res$cond_models)) {
    cm <- res$cond_models
    w("## Within-condition models")
    w("")
    w("Each condition modelled on its own: `indexSelected ~ meanVal_c * ", noise,
      " + (random | participant_id)`. The experience condition is the primary ",
      "model; the average condition is fitted identically for comparison.")
    w("")
    for (cond in cm$order) {
      st <- cm$structures %>% filter(condition == cond)
      ov <- cm$overall    %>% filter(condition == cond)
      an <- cm$anova      %>% filter(condition == cond)
      sl <- cm$slopes     %>% filter(condition == cond)
      ct <- cm$contrasts  %>% filter(condition == cond)

      w("### ", cond, " condition")
      w("")
      w("Random effects: ", st$rand_used[1],
        if (isTRUE(st$singular[1])) " (singular fit)" else " (converged, non-singular)", ".")
      w("")
      w("- Responses tracked the objective mean overall: b = ", fmt_num(ov$slope[1], 3),
        ", SE = ", fmt_num(ov$SE[1], 3),
        ", 95% CI [", fmt_num(ov$ci_low[1], 3), ", ", fmt_num(ov$ci_high[1], 3), "].")
      w("- Objective mean: ", f_line(get_effect(an, "meanVal_c")), ".")
      w("- Objective mean x ", nice, ": ", f_line(get_effect(an, paste0("meanVal_c:", noise))), ".")
      w("")
      w("Slopes by ", nice, ":")
      w("")
      for (i in seq_len(nrow(sl))) {
        w("- ", nice, " ", chr(sl[[noise]][i]), ": b = ", fmt_num(sl$slope[i], 3),
          ", SE = ", fmt_num(sl$SE[i], 3),
          ", 95% CI [", fmt_num(sl$ci_low[i], 3), ", ", fmt_num(sl$ci_high[i], 3), "].")
      }
      w("")
      if (nrow(ct)) {
        w("Simple-slope comparisons (Tukey-adjusted):")
        w("")
        for (i in seq_len(nrow(ct))) {
          w("- ", chr(ct$contrast[i], noise), ": estimate = ", fmt_num(ct$estimate[i], 3),
            ", SE = ", fmt_num(ct$SE[i], 3), ", ", fmt_p(ct$p.value[i]), ".")
        }
        w("")
      }
    }
  }

  # ---------------- LMM ----------------
  w("## Combined model (both conditions)")
  w("")
  w("`", res$lmm$formula, "`")
  w("")
  w("Random-effects structure: ", res$lmm$rand_used,
    if (isTRUE(res$lmm$singular)) " (singular fit; kept for the theoretically relevant structure)" else " (converged, non-singular)", ".")
  w("")
  la <- res$lmm$anova
  w("- Objective mean: ", f_line(get_effect(la, "meanVal_c")), ".")
  w("- Objective mean x ", nice, ": ", f_line(get_effect(la, paste0("meanVal_c:", noise))), ".")
  if (two) {
    w("- Objective mean x condition: ", f_line(get_effect(la, "meanVal_c:condition")), ".")
    w("- Objective mean x ", nice, " x condition: ",
      f_line(get_effect(la, paste0("meanVal_c:", noise, ":condition"))), ".")
    w("- Main effect of condition: ", f_line(get_effect(la, "condition")), ".")
  }
  w("")
  w("Estimated slopes of the objective mean (1 = perfect tracking, < 1 = regression to the mean):")
  w("")
  sl <- res$lmm$slopes
  for (i in seq_len(nrow(sl))) {
    lab <- if (two) paste0(chr(sl$condition[i]), ", ") else ""
    w("- ", lab, nice, " ", chr(sl[[noise]][i]), ": b = ", fmt_num(sl$slope[i], 3),
      ", SE = ", fmt_num(sl$SE[i], 3),
      ", 95% CI [", fmt_num(sl$ci_low[i], 3), ", ", fmt_num(sl$ci_high[i], 3), "].")
  }
  w("")
  ct <- res$lmm$contrasts %>% filter(comparison_set == "noise_within_condition")
  if (nrow(ct)) {
    w("Slope differences across ", nice, " (Tukey-adjusted):")
    w("")
    for (i in seq_len(nrow(ct))) {
      lab <- if ("condition" %in% names(ct)) paste0(chr(ct$condition[i]), ", ") else ""
      w("- ", lab, chr(ct$contrast[i], noise), ": estimate = ", fmt_num(ct$estimate[i], 3),
        ", SE = ", fmt_num(ct$SE[i], 3), ", ", fmt_p(ct$p.value[i]), ".")
    }
    w("")
  }
  cb <- res$lmm$contrasts %>% filter(comparison_set == "condition_within_noise")
  if (nrow(cb)) {
    w("Condition differences in slope at each level of ", nice, ":")
    w("")
    for (i in seq_len(nrow(cb))) {
      w("- ", nice, " ", chr(cb[[noise]][i]), ": estimate = ", fmt_num(cb$estimate[i], 3),
        ", SE = ", fmt_num(cb$SE[i], 3), ", ", fmt_p(cb$p.value[i]), ".")
    }
    w("")
  }

  # ---------------- reverse direction ----------------
  if (!is.null(res$reverse)) {
    rv <- res$reverse
    w("## Reverse direction (objective mean ~ report)")
    w("")
    w("Galton's own direction: given the report, what was actually out there. ",
      "`meanVal ~ resp_c * ", noise, if (two) " * condition" else "",
      " + (random | participant_id)`, with the report centred within participant. ",
      "Under regression to the mean this slope is also below 1; reporting both ",
      "directions is what separates compression from a scaling artefact in either variable.")
    w("")
    for (mdl in rv$order) {
      st <- rv$structures %>% filter(model == mdl)
      ov <- rv$overall    %>% filter(model == mdl)
      an <- rv$anova      %>% filter(model == mdl)
      sl <- rv$slopes     %>% filter(model == mdl)

      w("### ", if (mdl == "combined") "both conditions" else paste(mdl, "condition"))
      w("")
      w("Random effects: ", st$rand_used[1],
        if (isTRUE(st$singular[1])) " (singular fit)" else " (converged, non-singular)", ".")
      w("")
      w("- Overall slope of the report on the objective mean: b = ", fmt_num(ov$slope[1], 3),
        ", SE = ", fmt_num(ov$SE[1], 3),
        ", 95% CI [", fmt_num(ov$ci_low[1], 3), ", ", fmt_num(ov$ci_high[1], 3), "].")
      w("- Report: ", f_line(get_effect(an, "resp_c")), ".")
      w("- Report x ", nice, ": ", f_line(get_effect(an, paste0("resp_c:", noise))), ".")
      if (mdl == "combined" && two) {
        w("- Report x condition: ", f_line(get_effect(an, "resp_c:condition")), ".")
        w("- Report x ", nice, " x condition: ",
          f_line(get_effect(an, paste0("resp_c:", noise, ":condition"))), ".")
      }
      w("")
      w("Slopes by ", nice, ":")
      w("")
      for (i in seq_len(nrow(sl))) {
        lab <- if ("condition" %in% names(sl) && !is.na(sl$condition[i]))
                 paste0(chr(sl$condition[i]), ", ") else ""
        w("- ", lab, nice, " ", chr(sl[[noise]][i]), ": b = ", fmt_num(sl$slope[i], 3),
          ", SE = ", fmt_num(sl$SE[i], 3),
          ", 95% CI [", fmt_num(sl$ci_low[i], 3), ", ", fmt_num(sl$ci_high[i], 3), "].")
      }
      w("")
      ct <- rv$contrasts %>% filter(model == mdl, comparison_set == "noise_within_condition")
      if (nrow(ct)) {
        w("Slope differences across ", nice, " (Tukey-adjusted):")
        w("")
        for (i in seq_len(nrow(ct))) {
          lab <- if ("condition" %in% names(ct) && !is.na(ct$condition[i]))
                   paste0(chr(ct$condition[i]), ", ") else ""
          w("- ", lab, chr(ct$contrast[i], noise), ": estimate = ", fmt_num(ct$estimate[i], 3),
            ", SE = ", fmt_num(ct$SE[i], 3), ", ", fmt_p(ct$p.value[i]), ".")
        }
        w("")
      }
      cbv <- rv$contrasts %>% filter(model == mdl, comparison_set == "condition_within_noise")
      if (nrow(cbv)) {
        w("Condition differences in slope at each level of ", nice, ":")
        w("")
        for (i in seq_len(nrow(cbv))) {
          w("- ", nice, " ", chr(cbv[[noise]][i]), ": estimate = ", fmt_num(cbv$estimate[i], 3),
            ", SE = ", fmt_num(cbv$SE[i], 3), ", ", fmt_p(cbv$p.value[i]), ".")
        }
        w("")
      }
    }
  }

  # ---------------- exaggeration ----------------
  w("## Exaggeration analysis")
  w("")
  w("Responses below ", EXAGG_LOW_RESP, " for objective means under ", EXAGG_LOW_MEAN,
    ", and above ", EXAGG_HIGH_RESP, " for objective means over ", EXAGG_HIGH_MEAN,
    ", were counted as exaggerated; the proportion per participant and ", nice,
    " was entered into the same mixed ANOVA.")
  w("")
  es <- res$exagg$summary
  for (cond in levels(droplevels(es$condition))) {
    part <- es %>% filter(condition == cond)
    w("- ", cond, ": mean proportion = ",
      paste(sprintf("%s (%s)", fmt_num(part$mean_prop, 3), chr(part[[noise]])), collapse = ", "), ".")
  }
  w("")
  ea <- res$exagg$anova
  w("- Main effect of ", nice, ": ", f_line(get_effect(ea, noise)), ".")
  if (two) {
    w("- Main effect of condition: ", f_line(get_effect(ea, "condition")), ".")
    w("- ", nice, " x condition: ", f_line(get_effect(ea, paste0("condition:", noise))), ".")
  }
  w("")
  eph <- res$exagg$posthoc %>% filter(comparison_set == "noise_within_condition")
  if (!nrow(eph)) eph <- res$exagg$posthoc %>% filter(comparison_set == "noise_overall")
  if (nrow(eph)) {
    w("Pairwise comparisons (Tukey-adjusted):")
    w("")
    for (i in seq_len(nrow(eph))) {
      lab <- if ("condition" %in% names(eph)) paste0(chr(eph$condition[i]), ", ") else ""
      w("- ", lab, chr(eph$contrast[i], noise), ": difference = ", fmt_num(eph$estimate[i], 3),
        ", ", fmt_p(eph$p.value[i]), ".")
    }
    w("")
  }

  # ---------------- tails ----------------
  if (!is.null(res$tails)) {
    tf <- res$tails$fixed
    tm <- res$tails$matched
    w("## What lies behind an extreme report")
    w("")
    w("Two ways of looking at the tails. **Fixed cutoff**: trials whose report ",
      "crosses the exaggeration thresholds (< ", EXAGG_LOW_RESP, " or > ", EXAGG_HIGH_RESP,
      "), and the objective mean behind them. **Matched**: the most extreme ",
      round(tm$summary$tail_prop[1] * 100), "% of responses per side *within each cell*, ",
      "so the selection rate is the same at every noise level; the ratio ",
      "|objective deviation| / |response deviation| says how much real signal backs ",
      "a unit of reported extremity.")
    w("")
    w("### Fixed cutoff")
    w("")
    for (tl in unique(tf$means$tail)) {
      part <- tf$means %>% filter(tail == tl)
      w("- reports ", if (tl == "low") paste0("< ", EXAGG_LOW_RESP) else paste0("> ", EXAGG_HIGH_RESP),
        ": objective mean = ",
        paste(sprintf("%s (%s)", fmt_num(part$emmean, 2), chr(part[[noise]])), collapse = ", "), ".")
      an <- tf$anova %>% filter(tail == tl)
      w("  - Effect of ", nice, ": ", f_line(get_effect(an, noise)), ".")
      ct <- tf$contrasts %>% filter(tail == tl)
      for (i in seq_len(nrow(ct))) {
        w("  - ", chr(ct$contrast[i], noise), ": estimate = ", fmt_num(ct$estimate[i], 3),
          ", ", fmt_p(ct$p.value[i]), ".")
      }
    }
    if (!is.null(tf$window)) {
      w("")
      w("- Window bracketed by an extreme report (high tail - low tail): ",
        paste(sprintf("%s (%s)", fmt_num(tf$window$window, 2), chr(tf$window[[noise]])),
              collapse = ", "), " scale units.")
    }
    w("")
    w("### Matched tails")
    w("")
    for (cond in levels(droplevels(tm$summary$condition))) {
      part <- tm$summary %>% filter(condition == cond)
      w("- ", cond, ": ratio = ",
        paste(sprintf("%s (%s)", fmt_num(part$ratio, 3), chr(part[[noise]])), collapse = ", "),
        "; mean |response deviation| = ",
        paste(sprintf("%s (%s)", fmt_num(part$mean_abs_resp, 2), chr(part[[noise]])), collapse = ", "), ".")
    }
    w("")
    w("- Effect of ", nice, " on the ratio: ", f_line(get_effect(tm$anova, noise)), ".")
    if (two)
      w("- ", nice, " x condition: ", f_line(get_effect(tm$anova, paste0("condition:", noise))), ".")
    w("")
    wn <- res$tails$windows
    if (!is.null(wn)) {
      ce0 <- wn$centres
      w("### Symmetric report windows")
      w("")
      w("Trials where the report fell within +/-", wn$halfwidth, " of ", ce0[["low"]],
        " or of ", ce0[["high"]], ". Unlike the fixed cutoffs above, the two windows sit ",
        "symmetrically about the scale centre, so the low and high tails are treated alike. ",
        "This is the sensitive form of the reverse-slope question: does a given extreme ",
        "report back less extreme reality as noise rises?")
      w("")
    }
    if (!is.null(wn) && !is.null(wn$coverage) && any(!wn$coverage$fitted)) {
      sk <- wn$coverage %>% filter(!fitted)
      w("_Report window", if (nrow(sk) > 1) "s" else "", " ",
        paste(sprintf("~%g", unname(wn$centres[sk$window])), collapse = " and "),
        " skipped: too few trials (smallest cell had ", paste(sk$min_cell_n, collapse = ", "),
        ", minimum ", wn$min_trials, ")._")
      w("")
    }
    if (!is.null(wn) && nrow(wn$means)) {
      ce <- wn$centres
      for (wd in unique(wn$means$window)) {
        part <- wn$means %>% filter(window == wd)
        w("- reported ~", ce[[wd]], ": objective mean = ",
          paste(sprintf("%s (%s)", fmt_num(part$emmean, 2), chr(part[[noise]])), collapse = ", "), ".")
        an <- wn$anova %>% filter(window == wd)
        if (nrow(an)) w("  - Effect of ", nice, ": ", f_line(get_effect(an, noise)), ".")
        ct <- wn$contrasts %>% filter(window == wd)
        for (i in seq_len(nrow(ct)))
          w("  - ", chr(ct$contrast[i], noise), ": estimate = ", fmt_num(ct$estimate[i], 3),
            ", ", fmt_p(ct$p.value[i]), ".")
      }
      if (!is.null(wn$width)) {
        w("")
        w("Reality bracketed by a ", wn$width$report_span[1], "-unit span of reports:")
        w("")
        for (i in seq_len(nrow(wn$width)))
          w("- ", nice, " ", chr(wn$width[[noise]][i]), ": ", fmt_num(wn$width$width[i], 2),
            " scale units (SE ", fmt_num(wn$width$se_width[i], 2), ").")
      }
      w("")
    }

    w("A drop in the fixed version with a flat matched ratio means the tails moved ",
      "because the whole response distribution compressed, not because extreme reports ",
      "became less informative.")
    w("")
  }

  # ---------------- two-stage ANOVAs ----------------
  if (!is.null(res$anovas)) {
    an <- res$anovas
    w("## Two-stage ANOVAs on the data itself")
    w("")
    w("Each participant x ", nice, " cell reduced to one number computed straight ",
      "from the trials, then a mixed ANOVA on those numbers (", nice,
      " within, condition between). No mixed model is involved, so these are a ",
      "check on whether the model's conclusions depend on its random-effects structure. ",
      "`ges` is generalised eta squared.")
    w("")
    for (m in unique(an$anova$measure)) {
      rows <- an$anova %>% filter(measure == m)
      mns  <- an$means %>% filter(measure == m)
      w("### ", rows$label[1])
      w("")
      for (cond in levels(droplevels(mns$condition))) {
        part <- mns %>% filter(condition == cond)
        w("- ", cond, ": ",
          paste(sprintf("%s (%s)", fmt_num(part$mean, 3), chr(part[[noise]])), collapse = ", "), ".")
      }
      w("")
      e <- get_effect(rows, noise)
      if (!is.null(e)) w("- Main effect of ", nice, ": ", f_line(e),
                         ", ges = ", fmt_num(e$ges, 3), ".")
      if (two) {
        e <- get_effect(rows, "condition")
        if (!is.null(e)) w("- Main effect of condition: ", f_line(e),
                           ", ges = ", fmt_num(e$ges, 3), ".")
        e <- get_effect(rows, paste0("condition:", noise))
        if (!is.null(e)) w("- ", nice, " x condition: ", f_line(e),
                           ", ges = ", fmt_num(e$ges, 3), ".")
      }
      w("")
      ph <- an$posthoc %>% filter(measure == m, comparison_set == "noise", p.value < .05)
      if (nrow(ph)) {
        w("Significant pairwise comparisons (Tukey-adjusted):")
        w("")
        for (i in seq_len(nrow(ph))) {
          lab <- if ("condition" %in% names(ph) && !is.na(ph$condition[i]))
                   paste0(chr(ph$condition[i]), ", ") else ""
          w("- ", lab, chr(ph$contrast[i], noise), ": estimate = ",
            fmt_num(ph$estimate[i], 3), ", ", fmt_p(ph$p.value[i]), ".")
        }
        w("")
      }
    }
    if (!is.null(res$anova_vs_lmm)) {
      cv <- res$anova_vs_lmm
      w("### Agreement with the mixed model")
      w("")
      w("Slope of the objective mean, per-participant OLS against the model estimate:")
      w("")
      for (i in seq_len(nrow(cv))) {
        lab <- if ("condition" %in% names(cv)) paste0(chr(cv$condition[i]), ", ") else ""
        w("- ", lab, nice, " ", chr(cv[[noise]][i]), ": OLS = ", fmt_num(cv$two_stage[i], 3),
          ", model = ", fmt_num(cv$lmm[i], 3),
          ", difference = ", fmt_num(cv$difference[i], 3), ".")
      }
      w("")
      w("Largest absolute difference: ",
        fmt_num(max(abs(cv$difference), na.rm = TRUE), 3), " slope units.")
      w("")
    }
  }

  w("## Files")
  w("")
  w("Tables: `descriptives.csv`, `exclusions.csv`, `correlations_*.csv`, `lmm_*.csv`, `exaggeration_*.csv`.  ")
  w("Figures: `fig1_tracking.png`, `fig2_slopes.png`, `fig3_predictions.png`, `fig4_exaggeration.png`.")
  invisible(path)
}
